name: Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Add cache id in environment variable
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - name: Use cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Material for MkDocs
        run: pip install mkdocs-material 
      - name: Build and deploy the website to GitHub Pages
        run: mkdocs gh-deploy --force
